// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB42y1tGYTroM4zxWs5mcQ6O-Nf5CganMk',
    appId: '1:721767673970:web:be64724792f5c26e4452eb',
    messagingSenderId: '721767673970',
    projectId: 'projecto-ami',
    authDomain: 'projecto-ami.firebaseapp.com',
    storageBucket: 'projecto-ami.appspot.com',
    measurementId: 'G-30FB92EJE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6SrDmVLNyJTQWAkQELkFG3TWNpOocvw0',
    appId: '1:721767673970:android:11d893c7b9e04b2d4452eb',
    messagingSenderId: '721767673970',
    projectId: 'projecto-ami',
    storageBucket: 'projecto-ami.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWLiNa7x0llJ-123MRB4xo456Z8NNAIe4',
    appId: '1:721767673970:ios:ad56de5b9558e9994452eb',
    messagingSenderId: '721767673970',
    projectId: 'projecto-ami',
    storageBucket: 'projecto-ami.appspot.com',
    iosBundleId: 'com.example.amiProjecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWLiNa7x0llJ-123MRB4xo456Z8NNAIe4',
    appId: '1:721767673970:ios:ad56de5b9558e9994452eb',
    messagingSenderId: '721767673970',
    projectId: 'projecto-ami',
    storageBucket: 'projecto-ami.appspot.com',
    iosBundleId: 'com.example.amiProjecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB42y1tGYTroM4zxWs5mcQ6O-Nf5CganMk',
    appId: '1:721767673970:web:ce34c0505e92be464452eb',
    messagingSenderId: '721767673970',
    projectId: 'projecto-ami',
    authDomain: 'projecto-ami.firebaseapp.com',
    storageBucket: 'projecto-ami.appspot.com',
    measurementId: 'G-L3CLK6DV3X',
  );
}
